package  DS;

import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;



import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

//import javax.swing.ImageIcon;

/*
 * shop.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class shop extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form shop */
	public static Toolkit TLK=Toolkit.getDefaultToolkit();
	public shop(UserTank ut) {
		this.ut=ut;
		initComponents();
		addWindowListener(new WindowAdapter(){
			public void windowClosing(WindowEvent event){
				escape1();
			}
		});
	}
	@SuppressWarnings("deprecation")
	public void escape1(){
		this.dispose();
		
		ut.tc.threadRobot.resume();
		ut.tc.threadRepaint.resume();
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		ImageIcon image1=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/5.png")); 
		ImageIcon image2=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/bomb.png")); 
		ImageIcon image3=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/redcross.png")); 
		ImageIcon image4=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/speed.png")); 
		ImageIcon image5=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/assitant.png")); 
		ImageIcon image6=new ImageIcon(shop.class.getClassLoader().getResource("Image/Item/shield_2.png")); 


		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		//jButton7 = new javax.swing.JButton();//????????????????????????????????
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		
		
		//setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setUndecorated(true);
		getRootPane().setWindowDecorationStyle(JRootPane.COLOR_CHOOSER_DIALOG); // 设置为简单对话框风格
		
		this.getContentPane().setBackground(Color.LIGHT_GRAY);
		setTitle("shop");
		setLocation(500,100);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMaximizedBounds(new java.awt.Rectangle(1000, 100, 400, 600));
		setMinimumSize(new java.awt.Dimension(250, 600));
		setResizable(false);
		
		jButton1.setIcon(image1);
		jButton1.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指
		jButton1.setText("20发");
		jButton1.setToolTipText("散弹，点击图片购买");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(image2);
		jButton2.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton2.setText(" 5发");
		jButton2.setToolTipText("地雷炮弹，点击图片购买");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		jButton3.setIcon(image3);
		jButton3.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton3.setText("10滴");
		jButton3.setToolTipText("补血，，点击图片购买");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		
		jButton4.setIcon(image4);
		jButton4.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton4.setText("加速");
		jButton4.setToolTipText("提速，点击图片购买");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setIcon(image5);
		jButton5.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton5.setText("帮手");
		jButton5.setToolTipText("助手，点击图片购买");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setIcon(image6);
		jButton5.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton6.setText("盾牌");
		jButton6.setToolTipText("盾牌，点击图片购买");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		//??????????????????????????????????????????????????????????????????????????????????????
	/*	jButton7.setCursor(TLK.createCustomCursor(Toolkit.getDefaultToolkit().createImage(shop.class.getResource("pointer.png")),new Point(0,0), ""));//鼠标手指

		jButton7.setText("退出");
		jButton7.setToolTipText("点击退出");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});*/
//???????????????????????????????????????????????????????????????????????
		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel1.setForeground(new java.awt.Color(0, 0, 255));
		jLabel1.setText("100 $");
		jLabel1.setToolTipText("100\u91d1\u5e01");

		jLabel2.setBackground(new java.awt.Color(204, 255, 204));
		jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel2.setForeground(new java.awt.Color(0, 0, 255));
		jLabel2.setText("100 $");
		jLabel2.setToolTipText("100\u91d1\u5e01");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel3.setForeground(new java.awt.Color(0, 0, 255));
		jLabel3.setText("80 $");
		jLabel3.setToolTipText("80\u91d1\u5e01");

		jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel4.setForeground(new java.awt.Color(0, 0, 255));
		jLabel4.setText("80 $");
		jLabel4.setToolTipText("80 \u91d1\u5e01");

		jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel5.setForeground(new java.awt.Color(0, 0, 255));
		jLabel5.setText("50 $");
		jLabel5.setToolTipText("50\u91d1\u5e01");

		jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel6.setForeground(new java.awt.Color(0, 0, 255));
		jLabel6.setText("50 $");
		jLabel6.setToolTipText("50 \u91d1\u5e01");

		jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24));
		jLabel7.setForeground(new java.awt.Color(255, 0, 0));
		jLabel7.setText("\u6b22\u8fce\u6765\u5230\u9053\u5177\u5546\u57ce");

		jLabel8.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel8.setText("\u5f53\u524d\u60a8\u7684\u91d1\u5e01\u4e3a\uff1a");

		jTextField1.setEditable(false);
		jTextField1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jTextField1.setForeground(new java.awt.Color(204, 0, 0));
		jTextField1.setBackground(Color.LIGHT_GRAY);
		jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));//?????????????????
		//jTextField1.setText("  0");
		jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1,
				1, 1));

		jLabel9.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel9.setText("\u91d1\u5e01");
		
		
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				67,
																				67,
																				67)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel8)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jTextField1,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(
																																jButton1)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				27,
																																				27,
																																				27)
																																		.addComponent(
																																				jLabel5))
																														.addComponent(
																																jButton3)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				22,
																																				22,
																																				22)
																																		.addComponent(
																																				jLabel3))
																														.addComponent(
																																jButton5)))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												19,
																												19,
																												19)
																										.addComponent(
																												jLabel1)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addComponent(
																												jLabel6))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addComponent(
																												jLabel4))
																						.addComponent(
																								jButton6)
																						.addComponent(
																								jButton4)
																						.addComponent(
																								jButton2)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel9)
																														.addComponent(
																																jLabel2)))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				82,
																				82,
																				82)
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				208,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(47, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(7, 7, 7)
										.addComponent(jLabel7)
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																56,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(5, 5, 5)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																58,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel1))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				jButton6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				56,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel2)))
										.addGap(48, 48, 48)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel8)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel9)))
										.addGap(110, 110, 110)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	@SuppressWarnings("deprecation")
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		if(ut.moneyNum.MoneyNumber>=100){
				
			ut.shieldNum.raisesShieldNumber(30);
			ut.moneyNum.MoneyNumber-=100;
			jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
			//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
			int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
			if(result==JOptionPane.NO_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
			}
			//tc.threadRobot.resume();
			}
			else{
				int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
				if(result2==JOptionPane.YES_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
				}
			}
		// TODO add your handling code here:
	}

	@SuppressWarnings("deprecation")
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		if(ut.moneyNum.MoneyNumber>=100){			
			ut.help();
			jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
			//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
			int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
			if(result==JOptionPane.NO_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
			}
			//tc.threadRobot.resume();
			}
			else{
				int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
				if(result2==JOptionPane.YES_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
				}
			}
		// TODO add your handling code here:
	}

	@SuppressWarnings("deprecation")
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		
		if(ut.tc.speedFlag!=0)
		{
			int resultFlag=JOptionPane.showConfirmDialog(null,"您已经交易过"+ut.tc.speedFlag+"次，现在您需要 "+(80+ut.tc.speedFlag*160)+"金币，才能购买，是否继续？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
			if(resultFlag==JOptionPane.YES_OPTION){
				if(ut.moneyNum.MoneyNumber>=(80+ut.tc.speedFlag*160)){
					
					ut.addSpeed();
					ut.moneyNum.MoneyNumber-=(80+ut.tc.speedFlag*160);
					jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
					ut.tc.speedFlag++;
					//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
					int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
					if(result==JOptionPane.NO_OPTION){
						this.dispose();
						ut.tc.threadRobot.resume();
						ut.tc.threadRepaint.resume();
					}
					//tc.threadRobot.resume();
					}
					else{
						int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
						if(result2==JOptionPane.YES_OPTION){
						this.dispose();
						ut.tc.threadRobot.resume();
						ut.tc.threadRepaint.resume();
						}
					}
			}
		}
		else {
			if(ut.moneyNum.MoneyNumber>=(80+ut.tc.speedFlag*160)){
				
				ut.addSpeed();
				ut.moneyNum.MoneyNumber-=(80+ut.tc.speedFlag*160);
				jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
				ut.tc.speedFlag++;
				//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
				int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
				if(result==JOptionPane.NO_OPTION){
					this.dispose();
					ut.tc.threadRobot.resume();
					ut.tc.threadRepaint.resume();
				}
				//tc.threadRobot.resume();
				}
				else{
					int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
					if(result2==JOptionPane.YES_OPTION){
					this.dispose();
					ut.tc.threadRobot.resume();
					ut.tc.threadRepaint.resume();
					}
				}
		}
		
		// TODO add your handling code here:// TODO add your handling code here:
	}

	@SuppressWarnings("deprecation")
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if(ut.moneyNum.MoneyNumber>=80){
			
			ut.tankHitPoint.raisesHitPoint(10);
			ut.changeSpeed();
			ut.moneyNum.MoneyNumber-=80;
			jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
			//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
			int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
			if(result==JOptionPane.NO_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
			}
			//tc.threadRobot.resume();
			}
			else{
				int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
				if(result2==JOptionPane.YES_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
				}
			}// TODO add your handling code here:
	}

	@SuppressWarnings("deprecation")
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if(ut.moneyNum.MoneyNumber>=50){
			ut.addSuperShots();
			//ut.superShotsNum+=5;
			ut.moneyNum.MoneyNumber-=50;
			jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
			//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
			int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
			if(result==JOptionPane.NO_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
			}
			//tc.threadRobot.resume();
			}
			else{
				int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
				if(result2==JOptionPane.YES_OPTION){
				this.dispose();
				ut.tc.threadRobot.resume();
				ut.tc.threadRepaint.resume();
				}
			}
		// TODO add your handling code here:
	}

	//@SuppressWarnings("deprecation")
	@SuppressWarnings("deprecation")
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if(ut.moneyNum.MoneyNumber>=50){
		//ut.addHydraShots();	
		ut.hydraShotsNum+=20;
		ut.moneyNum.MoneyNumber-=50;
		jTextField1.setText(String.valueOf(ut.moneyNum.MoneyNumber));
		//JOptionPane.showMessageDialog(null,"交易成功！","道具商城消息提醒",JOptionPane.YES_NO_CANCEL_OPTION);
		int result=JOptionPane.showConfirmDialog(null,"交易成功！是否继续交易？？" , "道具商城消息提醒",JOptionPane.YES_NO_OPTION );
		if(result==JOptionPane.NO_OPTION){
			this.dispose();
			ut.tc.threadRobot.resume();
			ut.tc.threadRepaint.resume();
		}
		//tc.threadRobot.resume();
		}
		else{
			int result2=JOptionPane.showConfirmDialog(null, "抱歉，您的金币不足，交易未成功！是否退出商城？？", "道具商场消息提醒", JOptionPane.YES_NO_OPTION);// TODO add your handling code here:
			if(result2==JOptionPane.YES_OPTION){
			this.dispose();
			ut.tc.threadRobot.resume();
			ut.tc.threadRepaint.resume();
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				TankClient tc=new TankClient();
				new shop(tc.ut);
				//new shop(ut);
				tc.lunchFrame();
				//new shop().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	//private javax.swing.JButton jButton7;//?????????????????????????????????
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	//int speedFlag=0;//????????????????????????????????????????????????????
	UserTank ut;
	// End of variables declaration//GEN-END:variables

}